//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dtp
    {
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> IdFines { get; set; }
        public Nullable<int> IdDrivers { get; set; }
        public string Licence { get; set; }
        public string VinNumber { get; set; }
        public Nullable<int> NumberREG { get; set; }
        public string OtherObjects { get; set; }
        public string Victim { get; set; }
        public string Description { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual licence licence1 { get; set; }
        public virtual PlaceFines PlaceFines { get; set; }
    }
}
