//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GBDDContainer : DbContext
    {
        public GBDDContainer()
            : base("name=GBDDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeSetSet> CodeSetSet1 { get; set; }
        public virtual DbSet<SubjectsSetSet> SubjectsSetSet1 { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
    }
}
