//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIBDDContainer : DbContext
    {
        public GIBDDContainer()
            : base("name=GIBDDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeSubj> CodeSubj { get; set; }
        public virtual DbSet<ColorCars> ColorCars { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<EngineType> EngineType { get; set; }
        public virtual DbSet<licence> licence { get; set; }
        public virtual DbSet<Manufacture> Manufacture { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transports> Transports { get; set; }
        public virtual DbSet<TypeOfDrive> TypeOfDrive { get; set; }
        public virtual DbSet<Dtp> Dtp { get; set; }
        public virtual DbSet<PlaceFines> PlaceFines { get; set; }
    }
}
