//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class licence
    {
        public int idDriver { get; set; }
        public Nullable<System.DateTime> licenceDate { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public string categories { get; set; }
        public string licenceNum { get; set; }
    
        public virtual Drivers Drivers { get; set; }
    }
}
