//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transports
    {
        public string VIN { get; set; }
        public Nullable<int> ID_Drivers { get; set; }
        public Nullable<int> Manuf { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> Engine_Type { get; set; }
        public string TypeOfDrive { get; set; }
    
        public virtual ColorCars ColorCars { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual EngineType EngineType { get; set; }
        public virtual Manufacture Manufacture { get; set; }
    }
}
